### ISSUE TITLE
Install instruction to review

### ISSUE THREAD

**Issue by fnx2k** [martinruenz/photostory#1]
Hallo Martin

I am really interested by this project. I had already started to work on something similar without thinking of blender.

For the install instruction, could you clarify the commands ?
A  `git -clone`  is missing for photostory (and I am getting confused between photostory and photo-selection directory)

Link https://docs.blender.org/manual/en/dev/preferences/addons.html is not working anymore

Finally, you should explain how to start the program

Hint:
For Qt >=5.9 check your system with qdiag ou qmake -v
if qmake -v returns :
  *qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory*
>Install Qt with `sudo apt install qt5-default`

MfG

**Comment by martinruenz** [comment]
Thanks for the feedback.

I fixed the broken link and added a quickstart section, which hopefully clarifies things a bit better.

See commit 963b68c2b89041de2455a16467321c1cf9e67ce6 and 957241ff384f8a9a17ab2189fb0b4ca53fe3160e .
