### ISSUE TITLE
Photostory addon missed in the list.

### ISSUE THREAD

**Issue by gray380** [martinruenz/photostory#2]
Hi,

Photostory has been compiled and copied to the blender:
```
/usr/share/blender/2.80/scripts/addons/io_photostory
├── assets
│   ├── floor.png
│   ├── gebco_08_rev_elev_21600x10800.png
│   └── world.topo.bathy.200409.3x21600x10800.jpg
├── helpers_geometry.py
├── helpers_views.py
├── __init__.py
├── layout.py
├── test_layouts.ipynb
└── world_map.py
```
Bit it missed in the Edit - Preference - Add-ons list to enable.
Search by 'Pho' shows nothing.

**Comment by martinruenz** [comment]
I didn't try to run with Blender 2.80 yet, there is a good chance that it is not compatible without some adjustments. Would you mind trying 2.79?

**Comment by Boerde** [comment]
Hi I got it running with blender 2.80 checkout my branch [change_api_for_blender_2.80](https://github.com/Boerde/photostory/tree/change_api_for_blender_2.80)
This is my first time working with blender so no guarantee that I did not delete some important stuff.
But I did succeed in creating a photostory.

**Comment by martinruenz** [comment]
Cool! I'll have a closer look next weekend. Do you want to create a pull request?

**Comment by martinruenz** [comment]
Thanks to @Boerde's changes photostory should run in blender 2.8 now. I assume this issue is resolved but feel free to re-open if issue persists.
